### ISSUE TITLE
Hello! Which one is more developed?

### ISSUE THREAD

**Issue by jestarray** [Raymonf/grandcheese#1]
Hi, I was a huge fan of grand chase and I wanna try to play with a private server with my friend for a little. 
I was wondering which one is the most developed grand chase emulator. I notice you have 2-3 repositories related to it:
https://github.com/Raymonf/GrandChaseSeasonV
https://github.com/Raymonf/GCV
https://github.com/Raymonf/grandcheese

which one is most up to date and the one i should build off of? Thank you very much
Also do you know where i can get the client side game also?

**Comment by Raymonf** [comment]
Hello! The answer is: none of them!

I recommend using official server binaries (available widely now if you know where to search).

The first one is a fork of another project that, to my knowledge, has never compiled.

The second one is a fork of another project that was very incomplete.

The third one (the current repository) is more of a core for an emulator than an actual emulator, so you won't get very far in-game. However, it should make for a fairly stable starting point, if you want to write an emulator.

**Comment by jestarray** [comment]
I'll try to look for the official server binaries, thanks So the 3rd one, grandcheese is the best one to use as a baseline?

**Comment by Raymonf** [comment]
More or less, yes.

在 2021年6月19日週六 下午7:24，jestarray ***@***.***> 寫道：
